### ISSUE TITLE
importing qudt triples

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#10]
As discussed in email, we want to grab the qudt triple archive from their Github page and add it to our server as another external file. Once that has been done, we can eliminate the "unit:" entries from Imports.ttl. I think the qudt: prefix definition can stay the same.

**Comment by touretzkyds** [comment]
Be sure to do this in the Devel knowledge graph first, and make sure it works there before making the change to the Demo knowledge graph which the public is relying on.

**Comment by touretzkyds** [comment]
The link I sent you: https://raw.githubusercontent.com/qudt/qudt-public-repo/master/vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl
appears to only have vocabulary and not schemas. So it might not be the right thing to use, or maybe just not sufficient. I think  you should poke around in the QUDT github repository and try to find some directions on how to install their stuff properly.

**Comment by nhadlaw** [comment]
Imported the proper QUDT.ttl file and now rdfs:label works for qudt schemas
