### ISSUE TITLE
inconsistent taxon info

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#13]
In the current Demo graph, Brassicalis is shown as an Order but if you hover over it, the definition says it's a Family. Below that is Bracicaceae, which we show as a Family but the definition says is a Tribe. Below that is Brassica, which we show as a Genus but the definition says is a Species. And below that is Brassica oleracea, which we show as a Species and the definition says is "Edible green plant in the cabbage family".

You can see similar inconsistencies with Zingiberales and its descendants.

Why are our taxonRank values inconsistent with the definition strings? Did we import thes data incorrectly, or is this another issue of poor quality control in WikiData?

**Comment by nhadlaw** [comment]
This is an issue with how I was attributing the definitions. I can fix this now.

**Comment by nhadlaw** [comment]
Ok the current version of demo2.html should have fixed this issue.
