### ISSUE TITLE
understanding wd, wdt, and p prefixes

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#14]
Consider this query:
````
SELECT * WHERE {
  BIND (wd:P6611 as ?x).
  ?x ?r ?y.
  }
````
It returns 112 results. If you change wd to wdt, then you get only one result. What is the relationship between wd:P6611 and wdt:P6611?

WikiData also uses the p: prefix to reference properties, and p:P611 has the same property as wdt:P611. What is the logic behind this set of prefixes?

**Comment by deyaliao** [comment]
[WikiData Prefixes NOTES.pdf](https://github.com/touretzkyds/KnowledgeGraphDemo/files/8849380/WikiData.Prefixes.NOTES.pdf)
I'm not sure if this helps or not, but here's what I found.

**Comment by touretzkyds** [comment]
Don't close a question someone else asked. Let the asker close it if they're satisfied with the answer.

**Comment by touretzkyds** [comment]
These notes and the link to the stackoverflow discussion are very helpful.

**Comment by deyaliao** [comment]
Sorry about closing the question––I remember Nelly talking about closing the issues she was done with last meeting, so I interpreted that wrong and thought that I could close it without telling you. I won't do that next time.

**Comment by touretzkyds** [comment]
Every team has its own way of doing things, and we're still figuring out what our conventions should be. Since closing an issue hides it in the issues list, it's better to leave it open until everyone is satisfied, unless it's some tiny thing that you clearly and definiteively fixed, e.g., fixing a typo or correcting a trivial bug.
