### ISSUE TITLE
adapting demo2 to the Devel database

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#15]
demo2 probably won't work on the Devel database because we've changed some of the properties, e.g., replaced kgo:taxonRank with a boltz:Qxxxx property.

Make a new version demo2d that works on Devel, so we can test it out before copying Devel into Demo.

**Comment by nhadlaw** [comment]
demo2d.html should now accommodate the hierarchy display to the Devel knowledge base.

**Comment by touretzkyds** [comment]
This is not working for me. See the errors in the console below. Also, you left some debugging code laying around that is printing "here" 1622 times on the console.

![demo2d](https://user-images.githubusercontent.com/1978092/173983036-e949f644-77c8-41ce-8864-74ccf22b7579.png)

**Comment by touretzkyds** [comment]
Actually, despite these errors on the console, the demo is working. It's just zoomed out so far that I couldn't see anything at all. But we should fix the uncaught promise errors anyway,

**Comment by nhadlaw** [comment]
I got rid of the debugging line. However, I'm not seeing the Uncaught (in promise) line right now after testing a lot of functionalities. Maybe that was occuring in the version I uploaded yesterday. I uploaded a newer one just now and if you still get this error is there a specific action that's causing it (i.e. clicking on a node) or does it just appear immediately?

**Comment by nhadlaw** [comment]
Also yes the graph is zoomed out far enough that it looks like barely anything is there which is what me and Deya are going to work on fixing

**Comment by touretzkyds** [comment]
The uncaught promise errors are still occurring after I downloaded the latest version of devel. They happen during page load, before I've had a chance to do anything. The first two happen about 2 seconds into the page load operation, and the third one happens about 1 second after that.

I Googled the error message and found this:
https://stackoverflow.com/questions/72494154/a-listener-indicated-an-asynchronous-response-by-returning-true-but-the-message

It looks like the problem is caused by an interaction between our demo and some of the plugins I have in my Chrome; probably the ad blocker stuff. Running the demo in an icognito window, which disables the plugins. eliminates the errors. So you can ignore this issue for now.
