### ISSUE TITLE
image display

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#17]
Some of the animal taxa in WikiData have images associated with them. Let's import those properties into our graph and work out a way to display them. This is a chance for you to start working with Cytoscape. You can make a demo3.html file in the devel branch of KnowledgeGraphDemo and work on this code without interfering with Nelly.

**Comment by deyaliao** [comment]
Update: all taxa (with images) have corresponding images in the [Data.ttl file](https://github.com/touretzkyds/KnowledgeGraphServer/blob/2a155032570422392545a8516e13a1399afa3921/dev/Data.ttl#L1684), with the image hyperlink under kgo:taxonImage. We can see this through the server using this query!

```
PREFIX kgo: <http://solid.boltz.cs.cmu.edu:3030/ontology/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 

  SELECT DISTINCT ?yLabel ?rLabel ?image WHERE {
    ?a kgo:taxonName "Animalia"@en.
    ?y kgo:subTaxonOf* ?a.
    ?y kgo:taxonName ?yLabel.
  	OPTIONAL{?y kgo:taxonImage ?image.}
  	?y kgo:taxonRank [rdfs:label ?rLabel] .  
  }
  ORDER BY ?yLabel
```

I'll work out display in the next couple days.

**Comment by touretzkyds** [comment]
Looks great! Having images will offer us lots of UI options to expore.

**Comment by deyaliao** [comment]
I noticed that [Cytoscape](https://js.cytoscape.org/#style/background-image) (if you scroll down, you'll see an example of where they use background-image) was able to successfully use Wikidata images without running into the CORS issue (I copied/pasted their example into ours and found that images were able to load). Essentially, the link they're using is the uploads.wikimedia link, whereas my original one was the common.wikimedia link, which is the "[Hotlinking](https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia/technical)" method that isn't recommended. To elaborate more, a random example is: the link https://commons.wikimedia.org/wiki/Special:FilePath/President%20Barack%20Obama.jpg reloads into https://upload.wikimedia.org/wikipedia/commons/8/8d/President_Barack_Obama.jpg when loaded, and the latter link is the only one that cytoscape takes, where as we were originally using the first one. I found some random algorithm online to map the original link to the right link within the Sparql query, and now it works. I've pushed my changes to demo2d.html. Here are some examples. 
<img width="1440" alt="Screen Shot 2022-06-22 at 5 05 45 PM" src="https://user-images.githubusercontent.com/61635230/175181101-73979a8b-6981-4013-b07f-d300a1cbf116.png">
<img width="1440" alt="Screen Shot 2022-06-22 at 5 05 34 PM" src="https://user-images.githubusercontent.com/61635230/175181114-0defaed9-6477-424d-bd23-5acfa1c2545c.png">

**Comment by touretzkyds** [comment]
Great work! The images look terrific.

Can you add some tooltip code that displays the image URL when the user hovers their mouse over the image? Also it might be nice for right-click to offer options like "Copy URL", "Copy image", and "Open image in new tab".

**Comment by deyaliao** [comment]
I've implemented both and pushed to the Github. I used a couple of external extensions to implement such functionalities, installed with npm? On my local system there's a giant node_modules folder that keeps track of all the libraries, but it seems like one is not supposed to upload this folder to Github. Let me know if the demo doesn't seem to work on your end. 

<img width="1440" alt="Screen Shot 2022-06-28 at 1 55 00 PM" src="https://user-images.githubusercontent.com/61635230/176286223-494c9994-0ba3-4fe4-bb41-7b7f72191500.png">

<img width="1440" alt="Screen Shot 2022-06-28 at 1 55 18 PM" src="https://user-images.githubusercontent.com/61635230/176286172-6fc399e8-2625-4359-8050-4fd27da2b0ff.png">

**Comment by deyaliao** [comment]
If you're running locally, I believe you're supposed to run "npm install" within a terminal located at this github repo (KnowledgeGraphDemo)

**Comment by touretzkyds** [comment]
We are not going to use node.js in this project. Whatever extensions you want to use should be copied into the external/ folder so they can be included as part of the github repository.

**Comment by deyaliao** [comment]
I believe NPM is just a tool that allows you to install third party libraries using the command line, and I thought it might be convenient using it since other people do when dependent on a large number of packages. I have already copied the exact external files into github, so it should work now.
