### ISSUE TITLE
navigation history display

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#23]
We want to maintain a clickable navigation history display in the area at the top of the screen where the search box and mode buttons are located. Suppose the user starts at "Collard greens" (Brassica oleracea) and navigates upward three steps so that the current node is Brassicales. (We'll be adding navigation buttons to move around; see #24.) This is what the nav display should look like: we show all the nodes above the current node (easy, since this is a tree), and nodes below the current node if they are on the path that brought us here. So if the user moves to a subling of the current node the downward part of the history will be cleared because we didn't reach that sibling by traveling upward.

![history](https://user-images.githubusercontent.com/1978092/172064482-21d9ed39-f383-4b49-a018-c0c0c08197d1.png)

So if the user is at Brassicales and they move laterally to Zingiberales, we'll display Zingiberales in red and there will be nothing below it in the history, but we'll always show the nodes above it.

All the concepts shown in the history should be clickable, allowing the user to make that concept the current concept.

This history thing will become more complicated when we start developing a relationship display mode (as opposed to this taxonomy display mode). @deyaliao will help with that.

**Comment by nhadlaw** [comment]
So in this example that you gave, when a user moves from Brassicales to Zingiberales, should this history look like:
Biota < Plantae < Brassicales < "Zingiberales" (in red)?
 
Also just to clarify this is the idea you were thinking: A user is at a node, in the navigation history we ALWAYS show the nodes above it and the curr node (in that order) and ONLY show the nodes below it if we traversed them to get to the curr node. For exampe, if the order a user proceeds through nodes looks something like this: Biota, Plantae, Brassicales we should only show these in the navigation. Versus, if a user proceeds through nodes such as Brassica oleracea, Brassica, Brassicaceae, Brassicales then show 
Biota, Plantae, Brassicales, Brassicaceae, Brassica, Brassica oleracea?

**Comment by touretzkyds** [comment]
Yes, that's how I think it should work. After you've implemented this we can all play around with it and see how it feels.

**Comment by nhadlaw** [comment]
If a user tries to get to a node that is a couple levels up of the curr node should there still be no "below" nodes displayed in the navigation history?

For example if a user moves from Musa to Zingiberales (where that is now the current node) should the display show:
Biota < Plantae < Zingiberales?

**Comment by touretzkyds** [comment]
I think the most useful thing would be to display the "below" nodes, so the user can see where they came from, even if they're jumping up multipe levels.

**Comment by nhadlaw** [comment]
Could we close this issue @touretzkyds ?

**Comment by touretzkyds** [comment]
Yes, this is done.
