### ISSUE TITLE
navigation arrow

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#24]
We want to keep experimenting with different ways of navigating the knowledge graph. I would like to add a navigation arrow for moving around in the hierarchy. Suppose the user started at the "Collard greens" concept (Brassica oleracea) and navigated up three steps to Brassicales. This is what the nav arrow should look like:

![nav-arrow](https://user-images.githubusercontent.com/1978092/172063248-f8e84db2-e6af-4b7b-a7b8-9daecd1fc9b8.png)

The up arrow takes us to the parent taxon and the left and right arrows take us to siblings. Siblings need to be ordered alphabetically, which we don't appear to be doing right now; see #22. The example above reflects the current ordering, not the sorted ordering.

The down arrow is the tricky case, because a taxon will typically have multiple subtaxa. What we need to do is maintain a navigation history (see #23) so we know how we reached the current node. If we reached the current taxon by going up from one of its children, then going down should take us back to that child. I've shown the child Brassicaceae in gray to indicate that it's an inferred destination, and that other children are available. But if it's the only child then it should be in normal black font, not gray, since we have no other choices in the down direction.

Users should be able to click on either the triangle or the text to navigate in the indicated direction.

This tool will be especially valuable if we're in property display mode, because the parents and children of the displayed node are not immediately accessible when we're displaying the node's properties.

**Comment by nhadlaw** [comment]
Ok sounds good, would you like this just to be in the corner of the display?

**Comment by touretzkyds** [comment]
Put it wherever you think looks good. We can always change it later.

**Comment by nhadlaw** [comment]
What happens if we aren't in property display mode? I.e. if a user just sees the hierarchy they technically aren't at a node so theres no meaning to going left,right, etc. Should this feature not be available if they are looking at the full hierarchy and only when we are zoomed in at a node? If not where should the left, right, down and up directions take us?

**Comment by touretzkyds** [comment]
For now, let's only display the navigation arrow when we're in property display mode.

**Comment by nhadlaw** [comment]
I was wondering if we could close this issue @touretzkyds ?

**Comment by touretzkyds** [comment]
Yes, I'll close it now. We have other issues dealing with navigation, but this one is done.
