### ISSUE TITLE
switching to WikiData taxon ranks

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#3]
Our taxons use imported WikiData identifiers, e.g., "Alligator" is boltz:Q530597. But our taxon ranks do not, e.g., "Genus" is currently kgo:Genus rather than the imported WikiData identifier boltz:Q34740. This is a problem: words like "genus", "order", and "family" have multiple meanings, so we should not be using them as concept identifiers.

We should replace all our taxon ranks (Species through Kingdom) with their WikiData equivalents, e.g., replace kgo:Genus with boltz:Q34740.

Do this in the Devel database so we don't break the existing demo code.

**Comment by deyaliao** [comment]
Hi, sorry this is a bit late, but after some debugging, I finally successfully added the nextHigherRank and nextLowerRank for all the taxonRanks, so this should now be a viable property on the server. Additionally, now all taxonRanks utilize the q-value system. The code is viewable [here](https://github.com/touretzkyds/KnowledgeGraphServer/blob/bb2903d0a836339c4d8feb509de42f9911c00bdc/dev/Data.ttl#L410), and the results of the query against the Devel server can be found by typing: 

PREFIX kgo: <http://solid.boltz.cs.cmu.edu:3030/ontology/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 

  SELECT DISTINCT ?yLabel ?rLabel ?nextHigh ?nextLow WHERE {
    ?a kgo:taxonName "Animalia"@en.
    ?y kgo:subTaxonOf* ?a.
    ?y kgo:taxonName ?yLabel.
    ?y kgo:taxonRank ?b .
    ?b rdfs:label ?rLabel .
  OPTIONAL{?b kgo:nextHigherRank [rdfs:label ?nextHigh]}
  OPTIONAL{?b kgo:nextLowerRank [rdfs:label ?nextLow]}
  }
  ORDER BY ?yLabel

**Comment by touretzkyds** [comment]
Well done. I just tried it and it works.

I had to fix the missing angle brackets <> in the PREFIX statements first. After that it worked fine.

Is it time to migrate the Devel graph over to replace the current Demo graph? If you and @nhadlaw agree that this would be a good time, then please go ahead and do it. We should also remove the now spurious triples from Arthur's initial animal test data while we're at it.

**Comment by deyaliao** [comment]
Nelly and I do agree that it would be good to migrate the Devel graph over, and I think she'll be working on that today, where I'll also start playing around with the Demo. We had a question about Arthur's triples however; do you want us to delete everything that Arthur wrote in regards to the animal taxonomy––and keep the plant taxonomies etc, or get rid of that too?

**Comment by touretzkyds** [comment]
Let's keep Arthur's species, including the plants and bacteria, but make sure they're coded the same way as the species you've been importing. He had some ersatz Animal class that he cooked up for our initial testing but we should no longer be using. Let's also keep Arthur's other triples for now, like the corporation info, if they don't conflict with our newer stuff.
