### ISSUE TITLE
property display issues

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#30]
In the latest devel version of demo2, click on the Alligator node and we see its properties. Now, some bugs:

1. If we hover over some random faded-out blue taxon node, we still get a tooltip for it. Tooltips for bue nodes should be turned off in this context.

2. Click on the "Felis catis" node two nodes to the right of Alligator. Now we see its properties, but Alligator's properties are still displayed (though now faded). This is not correct behavior. When we're in property display mode, nothing that is faded out should be clickable.

**Comment by nhadlaw** [comment]
Latest version of demo2.html fixed both of these issues
