### ISSUE TITLE
smarter layout for purple nodes

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#31]
When we click on an orange box node and display its components as purple nodes, they are spaced evenly around the circle, e.g., if there are three of them then they are spaced 120 degrees apart. This looks nice. But we can be even smarter. Consider this display:

![b1](https://user-images.githubusercontent.com/1978092/172508029-0dda39e0-bf48-4edd-870b-97fd3b61ae13.png)

The incoming averageLifespan link is very close to the outgoing timeRetrieve link. We can improve the layout by adjusting the phase of the purple nodes (defining "phase" as the angle of the topmost node relative to vertical) so that the incoming arrow from the box node falls exactly between two of the purple nodes.

**Comment by nhadlaw** [comment]
Newest version of demo2.html should fix this version

**Comment by nhadlaw** [comment]
Fix this issue*
