### ISSUE TITLE
zoom rate

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#33]
In the Cytoscape display I can use the scroll wheel to zoom in or out. But the zoom rate is too high: a single click of the scroll wheel can make the image too big or too small, so I can't get it "just right".

Is there a way to reduce the zoom scale increment so that I can make finer adjustments?

**Comment by nhadlaw** [comment]
I just pushed a version of demo2d that should adjust the zoom rate. All I added was this line:
 "wheelSensitivity: 0.4"
where I define the Cytoscape graph so if this still needs to be adjusted, it should be very easy.

**Comment by touretzkyds** [comment]
This is so much better! Thanks.
