### ISSUE TITLE
server cleanup

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#34]
Currently the Devel knowledge graph is in KnowledgeGraph\Devel on SOLID, but the Demo knowledge graph is in KnowledgeGraph.

We should move the Demo knowledge graph to a new folder KnowledgeGraph\Demo and adjust the config files accordingly. This will make things more uniform and sensible.

Also let's create another knowledge graph called KnowledgeGraph\Scratch that can be used for random experimentation. We'll continue to use Devel for large development efforts, but if we just want to test out some random thing, we can mess around with Scratch without disrupting anything important.

**Comment by nhadlaw** [comment]
Which files would you like to be added to the scratch folder

**Comment by touretzkyds** [comment]
Let's use the current Devel graph for the initial Scratch graph.
