### ISSUE TITLE
taxon name input cleanup

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#36]
We need to clean up the input we receive in the taxon name text box. Delete any leading or trailing whitespace. Replace any internal whitespace (spaces or tabs) with a single space. Otherwise the name lookup will fail, as just happened to me when I left a trailing space on a genus name.

**Comment by nhadlaw** [comment]
The latest version of demo2d.html should fix this issue.

**Comment by touretzkyds** [comment]
Works great.
