### ISSUE TITLE
bad data: Q105034537 Osteolaemus

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#38]
In the Devel graph, boltz:Q729 "Osteolamus", a genus of cocodile, has skos:prefLabel "Holotrichia hybrida", which is a type of beetle. That's not right.

**Comment by deyaliao** [comment]
I'm a bit confused on where you're seeing this? The Devel graph uses information from Data.ttl, right? I don't believe to see "Osteolamus" anywhere in the Data.ttl file or demo, and boltz:Q729 is the Q-value identifier for "Animalia".

**Comment by touretzkyds** [comment]
Sorry, my mistake on the Q number: Ostelaemus (note the correct spelling, with an "e") is http://solid.boltz.cs.cmu.edu:3030/data/Q105034537

Here is what I'm seeing:
![Osteolaemus](https://user-images.githubusercontent.com/1978092/175390007-a2070736-d99e-464b-84f1-47447e607f1c.png)

**Comment by deyaliao** [comment]
Oh, I do see it. I do remember another one of my taxa having a weird entry too, one that was different from the first couple of times I ran it. I think the algorithm I pulled to generate the image changed the order, but I fixed it.

**Comment by touretzkyds** [comment]
Osteolaemus is still messed up:

![Osteolaemus](https://user-images.githubusercontent.com/1978092/176810667-f711a8e7-15b4-4508-b35a-1a314c774ace.png)

The prefLabel and definition refer to an insect, but it's actually a reptile. And the typeSpecies link is pointing off into empty space.

**Comment by deyaliao** [comment]
It should be fixed now.

**Comment by touretzkyds** [comment]
The skos:definition and skos:prefLabel are good now, but the typeSpecies link disappeared and the taxonImage isn't rendering.

**Comment by touretzkyds** [comment]
Verified working now.
