### ISSUE TITLE
positioning of the green taxonrank node

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#40]
Let's be a little smarter about positioning of the green taxonrank node in property view mode. Right now we always put it exactly to the left of the taxon node. While this is the preferred position, if the parent taxon has many children and the current taxon is one of the rightmost of those children, the parent taxon can show up more to the left than above the current taxon. It can end up being obscured by the green taxonrank node.

So we should be a little smarter about placing the green taxonrank node. Pay attention to the positioning of the parent taxon node first. Then, if we can't put the green taxonrank node immediately to the left because it would cover the parent taxon, we should move it a bit clockwise or counterclockwise to avoid this. Let's move it counterclockwise so that it's always to the left of the taxonOf link pointing to the parent taxon.

**Comment by nhadlaw** [comment]
I made these changes in demo2d.html. I think it would be good to close this issue but I didn't want to do it until you were happy with it @touretzkyds.

**Comment by touretzkyds** [comment]
Yes, this looks good now.
