### ISSUE TITLE
don't check in broken code

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#45]
The current devel version of demo2d.html is broken because dependencies were added to files that are not part of the repository, such as cytoscape-context-menus. Furthermore, it looks like there was an attempt to convert demo2d to use node.js. Don't do that. I don't want this software to be dependent on node.js, and it should come packaged with all the necessary libraries; it should not load any libraries from external sources.

**Comment by deyaliao** [comment]
I fixed it.

**Comment by touretzkyds** [comment]
Thanks. The demo is working for me again.
