### ISSUE TITLE
demo2d is infinite looping again

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#46]
Using the latest demo2d in the devel branch, open the JavaScript console first. Then type "Animal" in the search box. The page goes into an infinite loop. If you wait a while, something eventually times out and we end up with an error message in the console pointing at line 2947 which reads `while (curr_node != root){`. Do not write unsafe code like this. What happens if we have a loop in the graph and never reach the root?

The safe way to do this is to add an iteration counter with a max limit of something like 10000 and write:
`while (curr_node !=root and ++iterations < MAX_ITER) {`
After the while loop you should check that curr_node == root, and if it's not then you know something failed.

We should always assume that the graph is corrupt, because as the demo gets more and more complicated, the likelihood of things breaking increases. So we need to adopt defensive programming practices to prevent catastrophic failures. This is especially true if students start modifying the demo on their own. They're going to mess up, so we need to make the code resilient and also demonstrate to them what good defensive programming looks like.

**Comment by touretzkyds** [comment]
This might be the source of the infinite loop. Just a guess.

![antho1](https://user-images.githubusercontent.com/1978092/176580658-55928535-31c9-4fea-9679-11318083f0b7.png)

**Comment by nhadlaw** [comment]
This issue should now be fixed. I just forgot to add the qval for the root node in an object. It didn't have anything to do with the Anthozoa node. I also added the safety check for the while loop like you instructed.

**Comment by touretzkyds** [comment]
I'm closing this issue, but see my comments in #51 about code safety.
