### ISSUE TITLE
Fixing double node names textbox entry

### ISSUE THREAD

**Issue by nhadlaw** [touretzkyds/KnowledgeGraphDemo#49]
Is there a way to replicate the regular hierarchy query to use the qvalue of a taxon instead of its name? Instead of 
                  BIND ("Animalia"@en AS ?root_name), I tried:  BIND (boltz:Q729 AS ?root_name) but I don't think that's correct.

Here's the original query:

SELECT DISTINCT ?root_name ?root ?root_rank ?parent_name ?parent ?parent_prefLabel
           ?child_name ?child ?child_prefLabel ?def ?root_def ?rank_name
              WHERE 
                { 
                  BIND ("${taxon_value}"@en AS ?root_name). 
                  ?root kgo:taxonName ?root_name .  
                  ?root kgo:taxonRank [rdfs:label ?root_rank] .
                  OPTIONAL {
                    ?root skos:definition ?root_def .
                  }
                  ?child kgo:subTaxonOf* ?root . 
                  ?child kgo:subTaxonOf ?parent . 
                  ?child kgo:taxonName ?child_name .
                  OPTIONAL {
                    ?child skos:definition ?def .
                  }
                  ?child kgo:taxonRank ?rank .
                  ?rank rdfs:label ?rank_name . 
                  ?parent kgo:taxonName ?parent_name .
  	              ?child skos:prefLabel ?child_prefLabel .
                  ?parent skos:prefLabel ?parent_prefLabel .
              }

**Comment by touretzkyds** [comment]
When posting code like the lines above, please use four backquote characters (```) to format it correctly. You can edit this comment in Github to see the formatting below, to see how it's done. The answer to your question is to eliminate ?root_name entirely and just do:
````
    BIND (boltz:Q729 AS ?root)
````

**Comment by touretzkyds** [comment]
I shouldn't have closed this. It's your question, so you should close it if you're satisfied with the answer.
