### ISSUE TITLE
Iguana bug

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#52]
Type "Iguana" in the search box and switch to Full view. Click on the Iguana node to enter the property viewer. Now:

1. Iguana shows a subTaxonOf link to Iguaninae. Click on that node.
2. Iguaninae shows a subTaxonOf link to Iguania. Click on that node.
3. Although you expect to end up at Iguania, you actually end up at Squamata, which is the parent of Iguania.

This is a bug.

**Comment by nhadlaw** [comment]
This issue is now fixed in the latest version of demo2d.html.
