### ISSUE TITLE
missing properties in Devel graph

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#60]
There are properties in the Demo graph like kgo:averageLifespan and kgo:prefComparisons that are missing from the Devel graph. Please restore these to the Devel graph as soon as possible.

**Comment by deyaliao** [comment]
I do believe I just restored these properties for the taxa that have them.

**Comment by touretzkyds** [comment]
Yes, this is fixed now. Thanks.
