### ISSUE TITLE
Progress on Dagre Algorithm

### ISSUE THREAD

**Issue by nhadlaw** [touretzkyds/KnowledgeGraphDemo#62]
Hello, 

This isn't really an issue but I wanted to share some progress on the new dagre algorithm I'm working on. I'm not finished yet but I got somewhat of a hierarchy to display algorithmically on a screen so I thought that was a good step to show. Tomorrow I want to work on fixing the node sibling issues so that all siblings are equally spaced and that parents are directly in the middle of their children. This part shouldn't be hard. The hard part, which I focused on today, was fixing node conflicts. Here's what I got
![image](https://user-images.githubusercontent.com/101290675/178643842-37c3db6f-e436-4076-808d-6f83fba8a6cd.png)

**Comment by touretzkyds** [comment]
This looks great!
