### ISSUE TITLE
display of strings

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#8]
In the property display in demo2, some values are concepts, while others are strings. When we display a string it should be enclosed in "double quotes" so the user can see that it's a string.

**Comment by nhadlaw** [comment]
What do you consider a concept versus a string? What would be an example?

**Comment by touretzkyds** [comment]
Click on the "Raw Response" button and look at the JSON. If a result entry has a type value of "uri" then it's a concept. If its type is "literal" then it's a string or a number. If its type is "bnode" then it's a box like b0.

**Comment by touretzkyds** [comment]
taxonRank and subTaxonOf have values that are concepts. taxonName has a value that is a string.

**Comment by nhadlaw** [comment]
Oh ok makes sense thank you
