### ISSUE TITLE
display of box properties

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#9]
Box properties should be displayed using the pred2Label if one is supplied. Only use pred2 if pred2Label is not available. For example, with Alligator sinensis box b0, the timeRetrieve property should be displayed as "timeRetrieve", not the full URI.

**Comment by nhadlaw** [comment]
The latest version of demo2.html I added around 15 minutes ago should address and fix this issue

**Comment by touretzkyds** [comment]
Looks good.
